// task_1/svelte/src/lib/components/CountryCodeInput.svelte
<script lang="ts">
	import type { FormEventHandler } from "svelte/elements";
	import { countryCodesContext } from "../contexts";

	let {
		value = $bindable(""),
		onInput,
	}: {
		value?: string;
		onInput?: FormEventHandler<HTMLInputElement>;
	} = $props();

	const options = countryCodesContext.get();
</script>

<label class="CountryCodeInput input-box country">
	<span>Search Country</span>
	<input placeholder="US" maxlength="2" list="countries" autocomplete="country" bind:value oninput={onInput} />
	<datalist id="countries">
		{#each options as option}
			<option>{option}</option>
		{/each}
	</datalist>
</label>

<style>
	input {
		text-transform: uppercase;
	}
</style>

// task_1/vue/components/CountryCodeInput.vue
<script setup lang="ts">
import { countryCodesContext } from "@/lib/contexts";

const value = defineModel<string>({
	default: "",
});

const emit = defineEmits<{
	(e: "input", value: string): void;
}>();

const options = countryCodesContext.get();
</script>

<template>
	<label class="CountryCodeInput input-box country">
		<span>Search Country</span>
		<input
			placeholder="US"
			maxlength="2"
			list="countries"
			autocomplete="country"
			v-model="value"
			@input="$emit('input', value)"
		/>
		<datalist id="countries">
			<option v-for="option in options" :key="option">{{ option }}</option>
		</datalist>
	</label>
</template>

<style scoped>
input {
	text-transform: uppercase;
}
</style>
